blank_issues_enabled: true
contact_links:
  - name: Questions and support
    url: https://github.com/iqm-finland/KQCircuits/discussions
    about: Ask a question or request support about KQCircuits usage
